# This workflow runs linters and formatters

name: Ruff

on:
  push:
    branches:
      - '**'

jobs:
  format-and-lint:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Poetry
      uses: Gr1N/setup-poetry@v8

    - name: Install library and dependencies
      run: |
        poetry run pip install --upgrade pip setuptools
        poetry install --no-interaction

    - name: Check pyproject.toml with Poetry
      run: |
          poetry check --strict

    - name: Lint and Format with Ruff
      run: |
        poetry run ruff format --diff .
        poetry run ruff check --fix .

    - name: Check Types with Mypy
      run: |
        poetry run mypy -p cy_serial_bridge