name: test

on: push

jobs:
  test:
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: Gr1N/setup-poetry@v9
      - name: Install project
        run: poetry install --no-interaction
      - name: Run Pytest
        run: poetry run pytest tests

        # Also run mypy since sometimes it can generate different errors on different platforms
      - name: Check Types with Mypy
        run: |
          poetry run mypy -p cy_serial_bridge
